CREATE TABLE `CLASS_CATEGORY` (
  `CATEGORY_ID` int NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(255) DEFAULT NULL,
  `PHOTO` varchar(1000) DEFAULT NULL,
  `DESCRIPTION` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `DISPLAY_ORDER` int DEFAULT NULL,
  `LEVEL` varchar(100) DEFAULT NULL,
  `DESCRIPTION_ITEMS_LIST` varchar(1000) DEFAULT NULL,
  PRIMARY KEY (`CATEGORY_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `CLASS` (
  `CLASS_ID` int NOT NULL AUTO_INCREMENT,
  `CATEGORY_ID` int NOT NULL,
  `DESCRIPTION` varchar(1000) DEFAULT NULL,
  `TITLE` varchar(100) DEFAULT NULL,
  `PHOTO` varchar(100) DEFAULT NULL,
  `PUBLISH_DATE` date DEFAULT NULL,
  `DISPLAY_ORDER` int DEFAULT NULL,
  PRIMARY KEY (`CLASS_ID`),
  KEY `CLASS_CLASS_CATEGORY_FK` (`CATEGORY_ID`),
  CONSTRAINT `CLASS_CLASS_CATEGORY_FK` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `CLASS_CATEGORY` (`CATEGORY_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=27 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `CLASS_RECIPE` (
  `CLASS_ID` int NOT NULL,
  `RECIPE_ID` int NOT NULL,
  PRIMARY KEY (`CLASS_ID`,`RECIPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `DELIVERY_METHOD` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(255) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `DISPLAY_ORDER` int DEFAULT NULL,
  `ICON` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `GALLERY` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `PHOTO` varchar(1000) DEFAULT NULL,
  `LABEL` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `PRICE` (
  `PRICE_ID` int NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` varchar(100) DEFAULT NULL,
  `PRICE` decimal(6,2) DEFAULT NULL,
  `ICON` varchar(100) DEFAULT NULL,
  `GREAT_VALUE` tinyint(1) DEFAULT NULL,
  `ADDITIONAL_INFO` varchar(255) DEFAULT NULL,
  `MULTIPLE_STUDENTS` tinyint(1) DEFAULT NULL,
  `MIN_STUDENTS_FOR_DISCOUNT` int DEFAULT NULL,
  `DISCOUNT_PERCENTAGE` float DEFAULT NULL,
  `ADDITIONAL_INFO_CART` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`PRICE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `RECIPE_CATEGORY` (
  `RECIPE_CATEGORY_ID` int NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`RECIPE_CATEGORY_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `RECIPE` (
  `RECIPE_ID` int NOT NULL AUTO_INCREMENT,
  `RECIPE_CATEGORY_ID` int NOT NULL,
  `TITLE` varchar(100) DEFAULT NULL,
  `DESCRIPTION` varchar(1000) DEFAULT NULL,
  `PHOTO` varchar(100) DEFAULT NULL,
  `VIDEO` varchar(100) DEFAULT NULL,
  `PUBLISH_DATE` date DEFAULT NULL,
  `DISPLAY_ORDER` int DEFAULT NULL,
  `KEYWORD` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`RECIPE_ID`),
  KEY `RECIPE_RECIPE_CATEGORY_FK` (`RECIPE_CATEGORY_ID`),
  CONSTRAINT `RECIPE_RECIPE_CATEGORY_FK` FOREIGN KEY (`RECIPE_CATEGORY_ID`) REFERENCES `RECIPE_CATEGORY` (`RECIPE_CATEGORY_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=65 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `ACCOUNT` (
  `EMAIL` varchar(200) NOT NULL,
  `FIRST_NAME` varchar(20) DEFAULT NULL,
  `LAST_NAME` varchar(60) DEFAULT NULL,
  `PASSWORD` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`EMAIL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `ORDER` (
  `ORDER_NUMBER` char(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `EMAIL` varchar(200) NOT NULL,
  `PAYMENT_METHOD_ID` char(3) DEFAULT NULL,
  `ORDER_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ORDER_NUMBER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `ORDER_CLASS` (
  `ORDER_NUMBER` char(20) DEFAULT NULL,
  `EMAIL` varchar(200) DEFAULT NULL,
  `CLASS_ID` tinyint DEFAULT NULL,
  `DELIVERY_METHOD_ID` tinyint DEFAULT NULL,
  `NUM_STUDENTS` tinyint DEFAULT NULL,
  `PRICE` decimal(6,2) DEFAULT NULL,
  `DISCOUNT_PERCENTAGE` decimal(6,2) DEFAULT NULL,
  `CLASS_DATE` datetime DEFAULT NULL,
  `PURCHASE_DATE` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `PAYMENT_METHOD` (
  `PAYMENT_METHOD_ID` char(3) NOT NULL,
  `DESCRIPTION` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `REVIEW` (
  `EMAIL` varchar(200) NOT NULL,
  `CLASS_ID` tinyint NOT NULL,
  `STARS` tinyint DEFAULT NULL,
  `REVIEW_TEXT` varchar(1000) DEFAULT NULL,
  `REVIEW_TITLE` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`EMAIL`,`CLASS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
